In [1]:
#Import the necessary packages
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from keras import Sequential
%matplotlib inline

Using TensorFlow backend.

In [2]:
df = pd.read_csv("sonar.csv", header=None)

In [3]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [4]:
print("Shape of df:",df.shape)

Shape of df: (208, 61)

In [5]:
df.isnull().sum()/df.shape[0]

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
21    0.0
22    0.0
23    0.0
24    0.0
25    0.0
26    0.0
27    0.0
28    0.0
29    0.0
     ...
31    0.0
32    0.0
33    0.0
34    0.0
35    0.0
36    0.0
37    0.0
38    0.0
39    0.0
40    0.0
41    0.0
42    0.0
43    0.0
44    0.0
45    0.0
46    0.0
47    0.0
48    0.0
49    0.0
50    0.0
51    0.0
52    0.0
53    0.0
54    0.0
55    0.0
56    0.0
57    0.0
58    0.0
59    0.0
60    0.0
Length: 61, dtype: float64

In [6]:
df.isnull().sum().sum()

0

In [7]:
print("Unique values for outcome:",df[60].unique())
print("\nPercentage of distribution for outcome-")
print(df[60].value_counts()/df.shape[0])

Unique values for outcome: ['R' 'M']

Percentage of distribution for outcome-
M    0.533654
R    0.466346
Name: 60, dtype: float64

In [8]:
#Checking the distinct datatypes in the dataset
print("Distinct DataTypes:",list(df.dtypes.unique()))

Distinct DataTypes: [dtype('float64'), dtype('O')]

In [9]:
#Create a temp dataset with the datatype of columns
temp = pd.DataFrame(df.dtypes)
temp.columns = ["DataType"]

In [10]:
float_columns = temp.index[temp.DataType == "float64"].values
float_columns

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59], dtype=int64)

In [11]:
temp

   DataType
0   float64
1   float64
2   float64
3   float64
4   float64
5   float64
6   float64
7   float64
8   float64
9   float64
10  float64
11  float64
12  float64
13  float64
14  float64
15  float64
16  float64
17  float64
18  float64
19  float64
20  float64
21  float64
22  float64
23  float64
24  float64
25  float64
26  float64
27  float64
28  float64
29  float64
..      ...
31  float64
32  float64
33  float64
34  float64
35  float64
36  float64
37  float64
38  float64
39  float64
40  float64
41  float64
42  float64
43  float64
44  float64
45  float64
46  float64
47  float64
48  float64
49  float64
50  float64
51  float64
52  float64
53  float64
54  float64
55  float64
56  float64
57  float64
58  float64
59  float64
60   object

[61 rows x 1 columns]

In [12]:
categorical_columns = temp.index[temp.DataType == "O"].values
print("Categorical column - \n",categorical_columns)

Categorical column -
 [60]

In [13]:
for column in categorical_columns:
    df[column] = np.where(df[column] == 'R',1,0)

In [14]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,1
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,1
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,1
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,1
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,1

In [15]:
temp

   DataType
0   float64
1   float64
2   float64
3   float64
4   float64
5   float64
6   float64
7   float64
8   float64
9   float64
10  float64
11  float64
12  float64
13  float64
14  float64
15  float64
16  float64
17  float64
18  float64
19  float64
20  float64
21  float64
22  float64
23  float64
24  float64
25  float64
26  float64
27  float64
28  float64
29  float64
..      ...
31  float64
32  float64
33  float64
34  float64
35  float64
36  float64
37  float64
38  float64
39  float64
40  float64
41  float64
42  float64
43  float64
44  float64
45  float64
46  float64
47  float64
48  float64
49  float64
50  float64
51  float64
52  float64
53  float64
54  float64
55  float64
56  float64
57  float64
58  float64
59  float64
60   object

[61 rows x 1 columns]

In [16]:
df[target]

NameError: name 'target' is not defined

In [17]:
from sklearn.model_selection import train_test_split

target = 60

#split the final dataset into train and test with 80:20

x_train, x_test, y_train, y_test = train_test_split(df, df[target], test_size=0.2, random_state=2018)

#split the train dataset further into train and validation with 90:10
x_train, x_val, y_train, y_val = train_test_split(x_train,y_train,test_size=0.1,random_state=2018)

#Check the shape of each new dataset created
print("Shape of x_train:",x_train.shape)
print("Shape of x_test:",x_test.shape)
print("Shape of x_val:",x_val.shape)
print("Shape of y_train:",y_train.shape)
print("Shape of y_test:",y_test.shape)
print("Shape of y_val:",y_val.shape)

Shape of x_train: (149, 61)
Shape of x_test: (42, 61)
Shape of x_val: (17, 61)
Shape of y_train: (149,)
Shape of y_test: (42,)
Shape of y_val: (17,)

In [20]:
from keras import Sequential
from keras.layers import Dense

#Design the deep neural network [Small + 1 layer]
model  = Sequential()
model.add(Dense(60, input_dim = x_train.shape[1] ,activation="relu"))
model.add(Dense(1,activation = "sigmoid")) #activation = sigmoid for binary classification

model.compile(optimizer = "Adam",loss="binary_crossentropy",metrics=["accuracy"])

model.fit(x_train,y_train, validation_data = (x_val,y_val),epochs=3, batch_size=12)

Train on 149 samples, validate on 17 samples
Epoch 1/3

InternalError: GPU sync failed